name: smart_parking_solutions_rest
description: rest API for smart_parking_solutions
version: 0.0.1

publish_to: none

environment:
  sdk: ">=2.13.4 <=3.0.0"

dependencies:
  conduit: ^3.0.0
  mysql1: ^0.19.0
  smart_parking_solutions_common: ^0.0.6
  #path must be the directory of smart_parking_solutions_common's pubspec.yaml this may not be correct for everybody

dev_dependencies:
  test: ^1.0.0
  conduit_test: ^3.0.0
